### ISSUE TITLE
How can I run this project? (especially toy_mr with daqn)

### ISSUE THREAD

**Issue by watashihageteru** [chrisgrimm/deep_abstract_q_network#1]
How can I change train_dqn.py to learn toy_mr or four_rooms with daqn?

**Comment by melroderick** [comment]
We're currently working on cleaning things up and making it easier to change the configurations for running experiments.

But at the moment, the DAQN is all in the embedding_dqn directory. So, in embedding_dqn/train.py, uncomment the lines:

``# game = 'four_rooms'``
``# end_life_is_terminal = False``
``# train_hadooqn(*setup_four_rooms_env())``

and then run embedding_dqn/train.py.

**Comment by watashihageteru** [comment]
Dear Mr. Roderick

Thank you for your reply.
That helps me a lot.
I am also looking forward to the new release.

2018-08-12 2:54 GMT+09:00 Melrose Roderick <notifications@github.com>:
